//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using Entities;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AQLM2Entities : DbContext
    {
        public AQLM2Entities()
            : base("name=AQLM2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OKDesription> OKDesription { get; set; }
        public virtual DbSet<Pilote> Pilote { get; set; }
        public virtual DbSet<PiloteFini> PiloteFini { get; set; }
        public virtual DbSet<ValOKdIntegrtion> ValOKdIntegrtion { get; set; }
        public virtual DbSet<PiloteInteg> PiloteIntegs { get; set; }
        public virtual DbSet<PiloteFiniIntegration> PiloteFiniIntegrations { get; set; }
        public virtual DbSet<Equipe> Equipes { get; set; }
    }
}
