//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pilote_Fini
    {
        public int id { get; set; }
        public string Matricule { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string UF { get; set; }
        public string Fonction { get; set; }
        public string Poste { get; set; }
        public Nullable<int> idLigne { get; set; }
    
        public virtual LigneDem LigneDem { get; set; }
    }
}
