//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PiloteInteg
    {
        public string matricule { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string pwd { get; set; }
        public string poste { get; set; }
    }
}
